### ISSUE TITLE
Tab permalinking breaks all tabs

### ISSUE THREAD

**Issue by isaacaggrey** [blackbaud/skyux-tabs#101]
### Expected behavior
Setting permalinkId on `<sky-tabset>` should allow me to load a specific tab via page query param.

### Actual behavior
All tabs, except the first, are unreachable (click causes console error and doesn't load the selected tab) and the permalink doesn't work.

### Steps to reproduce

See [Stackblitz](https://stackblitz.com/edit/angular-bq2nfv-dvfnme?file=src%2Fapp%2Ftabs-demo.component.html) - all you need to do is set `permalinkId` and the other tabs will not load or become active when clicked.

### Severity

There's no workaround since you can't dynamically set the active tab due to https://github.com/blackbaud/skyux-tabs/issues/100. It may be a regression from version 3.2.4 which seems to have the correct/desired behavior once I pin to that version aside from showing the incorrect tab briefly fixed in https://github.com/blackbaud/skyux-tabs/issues/71.

### Impact

[AB#1554435](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1554435)

**Comment by Blackbaud-IsaacAggrey** [comment]
@Blackbaud-AlexKingman what additional information do you need to triage this? I see the `Needs: More info` tag applied to this issue and the Stackblitz demonstrates the problem on the latest version of @skyux/tabs.

**Comment by Blackbaud-IsaacAggrey** [comment]
Also, I don't know if this should be a separate issue but when I set the active tab dynamically via [active] on the `sky-tabset` - it doesn't appear that the query param of the permalink changes. See another [Stackblitz](https://stackblitz.com/edit/angular-bq2nfv-dbfel1)

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-IsaacAggrey We were unable to reproduce with the first stackblitz, but now I can clearly see the issue with your updated stackblitz link. Definitely something unexpected happening here. I'll remove the label. Thanks for following up!

**Comment by Blackbaud-SteveBrush** [comment]
Discovered the reason for the problem. Apparently, matrix parameters (or "optional route parameters") are not allowed on the root route. If you put the tabset on a child route, `permalinkId` works just fine (which is why it was difficult for me to reproduce this issue). We'll need to figure out a different solution it seems.
See: https://github.com/angular/angular/issues/9505#issuecomment-231429914
