### ISSUE TITLE
Tab focus is black instead of blue

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-tabs#131]
### Expected behavior

Tab focus should be blue
[Seems like in most cases there is a blue border around the focus field.  The tabs on the Add Person form have a black border.](https://blackbaud.slack.com/archives/CGB3BQQG3/p1599228549033900?thread_ts=1599221632.028900&cid=CGB3BQQG3)

### Actual behavior

Tab focus is black

### Steps to reproduce

Click around on the vertical tabs or sectioned form demo

### Severity

Low

### Impact

Low

[AB#1569675](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1569675)

**Comment by Blackbaud-SteveBrush** [comment]
We haven't added "modern" styles to tabs or vertical tabs yet; we'll address this at that time. Thanks!

**Comment by Blackbaud-DanGrochmal** [comment]
Thanks Steve!
