### ISSUE TITLE
Sky-Vertical-Tabset Errors when sky-vertical-tab removed

### ISSUE THREAD

**Issue by Blackbaud-JohnHolder** [blackbaud/skyux-tabs#22]
### Expected behavior
The sky-vertical-tabset component should support manipulation of the sky-vertical-tabs using standard structural directives like *ngFor, *ngIf, *ngSwitch, etc

### Actual behavior
When the sky-vertical-tabset component's sky-vertical-tabs are modified using structural directives, the component will error out and stop rendering properly under certain circumstances (common - I believe the errors will happen if the _active tab_ is ever manipulated)

### Steps to reproduce

```
<sky-vertical-tabset>
      <sky-vertical-tab tabHeading="tab 1" >
        Tab 1 content
      </sky-vertical-tab>
      <sky-vertical-tab *ngIf="!tabNotApplicable" tabHeading="tab 2" active="true">
        Tab 2 content
      </sky-vertical-tab>
      <sky-vertical-tab tabHeading="tab 3">
        Tab 3 content
      </sky-vertical-tab>
    </sky-vertical-tabset>
    <button type="button" (click)="tabNotApplicable=!tabNotApplicable">Click me</button>
```

render this html, click the button, first notice that the 'removed' content is still on the page - click on a different tab - view console and note that error is thrown and the tab content is now rendered in the wrong place

### Severity
High

### Impact
Cannot confidently use the Sky-Vertical-Tabset in common scenarios where the tabs are not static

**Comment by Blackbaud-ToddRoberts** [comment]
What's the scenario where you are removing tabs from the tabset?

**Comment by Blackbaud-JohnHolder** [comment]
Each report category defines different sections (tabs) of information to capture.  The user has the ability to change the category. The horizontal version of the tab component handles this scenario, so I was surprised when the vertical failed.

On Apr 23, 2019, at 11:20 AM, Blackbaud-ToddRoberts <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the scenario where you are removing tabs from the tabset?
