### ISSUE TITLE
Allowed sectioned form sections to be disabled

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux-tabs#46]
### Expected behavior

The sectioned form component uses the vertical tab component which has support for disabling a tab, we would love to be able to disable a sectioned form section as well.

### Actual behavior

The sectioned form component does not have support for disabling a section

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-GavinNicol Do you mind providing more information on your use case? What do you mean by "disabling a section"?

**Comment by Blackbaud-SteveBrush** [comment]
I spoke to Gavin offline; he's going to use the Wizard component instead.
