### ISSUE TITLE
Difficulty when attempting to load just the selected tab with permalink

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [blackbaud/skyux-tabs#66]
### Expected behavior
We have a page with a tabset where the content of the tabs is fairly heavy to load, so we trigger the load by listening to the tab change since that is the only way that we have found to hook in to which tab is loaded.  We've run into a few limitations that we've been unable to work around to load just the selected tab, which is either the first default tab or the tab selected via permalink.

- The desired behavior is that we would see a tab change event triggered for the initial page load for either the default first tab or for the permalink selected tab so we know exactly which tab is loaded and no others.
### Actual behavior
- When loading a page with the `[active]` property set (default set to 0), the tab change handler isn't triggered for that first tab, so we would have to load the first tab manually.
- When removing the `[active]` property, the tabset selects tab 0 by default and triggers the tab change. This works ok for loading the first tab, but it does conflict with the `[active]` property being required in the docs.
- When there is a permalink in the url, the tab change behavior is triggered so we can load the tab based on that, but if `[active]` is not set, it triggers the tab change for both tab 0 and then the selected tab, i.e. tab 1, so we see two tab change events and load both tabs immediately.
### Steps to reproduce
Description in actual behavior.
### Severity
Medium
### Impact
Unable to prevent heavy API requests on default first tab from triggering when loading other tab.

We could probably workaround by inspecting the route ourselves to observe if there is a permalink parameter set, but didn't want to duplicate the logic from the tabset.

**Comment by Blackbaud-SteveBrush** [comment]
This will need to be an opt-in feature since many consumer unit tests are querying the tab contents before activating the specific tab.
