### ISSUE TITLE
[active] input on tabset no longer matches to [tabIndex] values on tabs to set active state

### ISSUE THREAD

**Issue by IsaacBoy** [blackbaud/skyux-tabs#80]
### Expected behavior
when setting the [active] input on the tab set, as long as one of the tab children had that value as a "custom" [tabIndex] value, that would become the active tab

### Actual behavior
It doesn't do that. The behavior seems to have stopped working in this PR: https://github.com/blackbaud/skyux-tabs/pull/73

### Steps to reproduce
Simulate the scenario described above. In our case, `tabIndex` is a non-sequential number, but I don't think that matters

### Severity
Medium? a workaround would be to use the [active] bool input on the tab, and do the caparison matching ourselves; that seems to work

For example this used to work: https://blackbaud.visualstudio.com/Products/_git/skyux-spa-gmk?path=%2Fsrc%2Fapp%2F%23workspace%2Fworkspace.component.html&version=GBmaster&line=3&lineEnd=9&lineStartColumn=5&lineEndColumn=8&lineStyle=plain

Now we have to change it to something like this to work:
```
<sky-tabset (activeChange)="tabChanged($event)" (newTab)="addNewTabClick()">
      <sky-tab
        *ngFor="let tabInfo of allTabs"
        [tabIndex]="tabInfo.tabId"
        [tabHeading]="tabInfo.heading"
        [active]="tabInfo.tabId === activeTabId"
        (close)="closeTabClick(tabInfo.tabId)"
      >
```

### Impact
Grantmaking rewrite

[AB#1538592](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1538592)

**Comment by Blackbaud-SteveBrush** [comment]
More info around this issue: Setting the active state on a tab does not appear to work when the tabs array is compiled _after_ the `tabset` component is rendered on the screen.

A workaround is to prevent rendering of the tabset until the tabs array is compiled.

```
<sky-tabset *ngIf="tabArray.length > 0"
  [active]="activeTabIndex"
>
  <sky-tab *ngFor="let tab of tabArray"
    [tabIndex]="tab.tabIndex"
    [tabHeading]="tab.tabHeading"
  >
    {{ tab.tabContent }}
  </sky-tab>
</sky-tabset>

```

**Here's a StackBlitz to demonstrate the workaround:**
https://stackblitz.com/edit/angular-ijuwiq
