### ISSUE TITLE
3.6 -> 3.8 upgrade of @skyux/grids causes headingless columns to fail

### ISSUE THREAD

**Issue by Blackbaud-ChrisMecklenborg** [blackbaud/skyux-tabs#89]
### Expected behavior
Headingless columns continue to work.

### Actual behavior
Columns that don't include a heading value cause rendering to fail, preventing anything else on the page from completing as well.  (The problem is the `.trim()` that was added - it doesn't check for a null.)

### Steps to reproduce
Upgrade an existing project with a headingless column,
Serve it,
Navigate to the page with the grid.  (Interestingly, because of the way tabs are rendered, the blow up can occur even if the grid isn't visible.)

### Severity
High-ish?  It wouldn't be a big deal except that the way we bring in dependencies means that we're blocked from upgrading since some of the libraries we use, but our team doesn't own, have headingless columns.

### Impact
We changed the list in our project to have a blank header `" "`, but we still can't upgrade because there are three other projects we bring in on different tabs that all have a headingless column.  We can either coordinate with other teams to update those projects, and coordinate releases, or we can change grids to allow for null headings again - I'm hoping there's not a problem with that, since it's way, way less work.

**Comment by Blackbaud-DanMiller** [comment]
Fixed as of 3.8.1 and 4.0.1
